export enum TYPES_ENUM {
        CONTENT_TEXT = 'CONTENT_TEXT',
        CONTENT_VIDEO = 'CONTENT_VIDEO',
        FIT_TILES = 'FIT_TILES',
        MULTI_CHOOSE = 'MULTI_CHOOSE',
        SELECT_CORRECT_ANSWER = 'SELECT_CORRECT_ANSWER',
        SINGLE_CHOOSE = 'SINGLE_CHOOSE',
        TRUE_FALSE = 'TRUE_FALSE',
    }

export const PLAYABLE_QUESTION_TYPES: TYPES_ENUM[] = [
    TYPES_ENUM.FIT_TILES, 
    TYPES_ENUM.MULTI_CHOOSE, 
    TYPES_ENUM.SELECT_CORRECT_ANSWER, 
    TYPES_ENUM.SINGLE_CHOOSE, 
    TYPES_ENUM.TRUE_FALSE
];

export enum QUESTION_MEDIA_TYPES_ENUM {
    PHOTO = 'PHOTO',
    VIDEO = 'VIDEO',
}