export namespace Game {
    export enum PLAYER_ROLE {
        player = 'player',
        spectator = 'spectator',
    }

    export enum STATUS_ENUM {
        CREATED = 'CREATED',
        STARTED = 'STARTED',
        CANCELLED = 'CANCELLED',
        FINISHED = 'FINISHED',
    }

    export enum STAGE_ENUM {
        COMPETITION = 'COMPETITION',
        FINAL = 'FINAL', // not for questions
        INTRODUCTION = 'INTRODUCTION',
        KNOWLEDGE = 'KNOWLEDGE',
        QUICK_CONTENT = 'QUICK_CONTENT',
    }

    export const COMPETITION_STAGES = [STAGE_ENUM.COMPETITION, STAGE_ENUM.QUICK_CONTENT];
    export const MAX_POINTS_STAGES = [STAGE_ENUM.KNOWLEDGE, STAGE_ENUM.QUICK_CONTENT];

    export const GAME_FEEDBACK_FALLBACK_TIME_MS = 200;
    export const GAME_FEEDBACK_TIME_MS = 1000 * 4 + GAME_FEEDBACK_FALLBACK_TIME_MS;
    export const GAME_START_WAITING_TIME_MS = 1000 * 10;
}

export namespace Question {
    export enum TYPES_ENUM {
        CONTENT_INSTRUCTION = 'CONTENT_INSTRUCTION',
        CONTENT_INTRODUCTION = 'CONTENT_INTRODUCTION',
        CONTENT_QUESTION = 'CONTENT_QUESTION',
        CONTENT_TEXT = 'CONTENT_TEXT',
        CONTENT_TITLE = 'CONTENT_TITLE',
        FILL_IN_CORRECT_ORDER = 'FILL_IN_CORRECT_ORDER',
        FINAL = 'FINAL',
        FIT_TILES = 'FIT_TILES',
        LEADERBOARD = 'LEADERBOARD',
        LEFT_RIGHT = 'LEFT_RIGHT',
        MULTI_CHOOSE = 'MULTI_CHOOSE',
        SELECT_CORRECT_ANSWER = 'SELECT_CORRECT_ANSWER',
        SELECT_CORRECT_ORDER = 'SELECT_CORRECT_ORDER',
        SINGLE_CHOOSE = 'SINGLE_CHOOSE',
        TRUE_FALSE = 'TRUE_FALSE',
    }

    export const PLAYABLE_QUESTION_TYPES: TYPES_ENUM[] = [TYPES_ENUM.FILL_IN_CORRECT_ORDER, TYPES_ENUM.FIT_TILES, TYPES_ENUM.LEFT_RIGHT, TYPES_ENUM.MULTI_CHOOSE, TYPES_ENUM.SELECT_CORRECT_ANSWER, TYPES_ENUM.SELECT_CORRECT_ORDER, TYPES_ENUM.SINGLE_CHOOSE, TYPES_ENUM.TRUE_FALSE];

    export const LEADERBOARD_QUESTION_TYPES: TYPES_ENUM[] = [TYPES_ENUM.FINAL, TYPES_ENUM.LEADERBOARD];
}
